import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import React from 'react';

import { getRoleFromCookies } from '../src/lib/role-cookie';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dating',
  description: 'Generated by create next app',
  icons: '/icon.svg',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const role = await getRoleFromCookies();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='flex items-center justify-between border-b px-4 py-2 text-sm'>
          <Link className='font-semibold' href='/'>
            Dating
          </Link>
          <div>
            Role: <span className='font-mono'>{role}</span>{' '}
            <Link className='underline' href='/dev/role'>
              (switch)
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
