import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import React from 'react';

import './globals.css';
import { getSession } from '@/src/ports/auth';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Dating',
  description: 'Generated by create next app',
  icons: '/icon.svg',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Skip session loading during tests to prevent database connection issues
  const sess =
    process.env.NODE_ENV === 'test'
      ? null
      : await getSession().catch(() => null);
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='flex items-center justify-between border-b px-4 py-2 text-sm'>
          <div className='flex items-center gap-4'>
            <Link className='font-semibold' href='/'>
              Dating
            </Link>
            <nav className='flex items-center gap-3'>
              <Link href='/'>Home</Link>
              <Link href='/upload'>Upload</Link>
              <Link href='/moderate'>Moderate</Link>
              <Link href='/me'>My photos</Link>
            </nav>
          </div>
          <div className='flex items-center gap-1'>
            {sess ? (
              <>
                <span>User:</span>
                <span className='font-mono font-semibold'>{sess.userId}</span>
                <span className='font-mono'>({sess.role})</span>
                <Link className='underline' href='/dev/login'>
                  (switch)
                </Link>
                <form
                  action={async () => {
                    'use server';
                    const { clearSession } = await import('@/src/ports/auth');
                    const jar = await import('next/headers').then(m => m.cookies());
                    jar.delete('sb-access-token');
                    jar.delete('sb-refresh-token');
                    jar.delete('sb-user-email');
                    const projectRef = process.env.SUPABASE_PROJECT_REF;
                    if (projectRef) {
                      jar.delete(`sb-${projectRef}-auth-token`);
                    }
                    await clearSession();
                  }}
                  className='inline'
                >
                  <button
                    type='submit'
                    className='underline text-red-600 hover:text-red-800'
                  >
                    (sign out)
                  </button>
                </form>
              </>
            ) : (
              <>
                <span>Anon</span>
                <Link className='underline' href='/dev/login'>
                  (login)
                </Link>
                <Link className='underline' href='/dev/sb-login'>
                  (supabase)
                </Link>
              </>
            )}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
